### get all users
GET http://localhost:4000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoiNzFiNWMyY2QtYTQzMC00MGFlLWIwZmItZjFlYjRmYWZiN2ZjIiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkbjJ4ZGphekFJOEU0cUlYT1BkWURMdWtuSG9yNDhlTmRBQk1PaFh5OHBuOWM4TlNnQy9DeUsiLCJyb2xlIjoidXNlciIsInN0YXR1cyI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNi0wMi0xMVQwODo0MDowNy4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNi0wMi0xMVQwODo0MDowNy4wMDBaIiwibGFzdExvZ2luQXQiOm51bGx9LCJpYXQiOjE3NzA4MDAzMjksImV4cCI6MTc3MDgwMzkyOX0.ASCyn7C9jg0rCb3gpKvRjM2jYF8bhmrVaJ1Nz69emcM

### get user by id
GET http://localhost:4000/users/3b8a1469-ce1d-4f9d-8c6f-8bb467e05086
Content-Type: application/json

### post user
POST http://localhost:4000/users/registration
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@exmle.com",
  "password": "Jelszo123",
  "confirm": "Jelszo123"
}

### login
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "Jelszo123"
}

### update user by id
PATCH http://localhost:4000/users/3b8a1469-ce1d-4f9d-8c6f-8bb467e05086
Content-Type: application/json

{

    "name": "Pityu"

}
### DELETE user by id
DELETE http://localhost:4000/users/1c67cfac-14ee-4b1c-91c7-5057c3f33175